### ISSUE TITLE
How to serve static files?

### ISSUE THREAD

**Issue by dion-sony** [hviana/faster#4]
```
import {
  req,
  res,
  Server,
  serveStatic,
} from "https://deno.land/x/faster/mod.ts";

const port = parseInt(Deno.env.get("PORT") || "8080");


const server = new Server();

server.get(
    "/*",
    serveStatic("./dist"),
  );

console.log(`🚀 Listening on port ${port}: http://localhost:${port}`);
await server.listen({ port});
```

`./dist` is a regular web app, with `./dist/index.html` and other assets. This content is served by other file servers no problem.

This fails: with the browser pointing to http://localhost:3000

```
❯ PORT=3000 deno run --allow-all --unstable server.ts
🚀 Listening on port 3000: http://localhost:3000
Error: Is a directory (os error 21)
    at async read (ext:deno_io/12_io.js:108:17)
    at async Object.pull (https://deno.land/std@0.184.0/streams/readable_stream_from_reader.ts:59:22)
```

**Comment by hviana** [comment]
You are just pointing the static files directory. The system does not know that the route "/" is equivalent to "index.html". You also have to indicate the root route. I believe this might work:
server.get(
  "/",
  async (ctx: any, next: any) => {
    ctx.redirect("/index.html");
    await next();
  },
);

**Comment by hviana** [comment]
Or, also, using the redirection middleware:
server.get(
  "/",
  redirect("/Index.html"),
);

**Comment by hviana** [comment]
no activity

**Comment by hviana** [comment]
no activity
